#ifndef MARCCDREADER_H
#define MARCCDREADER_H


///////////////////////////////////////////////////////////
// YAT::TASK 
///////////////////////////////////////////////////////////
#include <yat/threading/Task.h>
#include <DiffractionImage.h>			//- to read back img data

///////////////////////////////////////////////////////////


#include <stdlib.h>
#include <limits>

#include "Debug.h"
#include "Data.h"
#include <base.h>
#include <file.h>

#include "HwMaxImageSizeCallback.h"
#include "MarccdCamera.h"
#include "HwBufferCtrlObj.h"


using namespace lima;
using namespace lima::Marccd;
using namespace std;



namespace lima
{
namespace Marccd
{

/*******************************************************************
 * \class Reader
 * \brief object involved reading/watching CBF files generated by Pilatus
 *******************************************************************/

class Reader : public yat::Task
{
    DEB_CLASS_NAMESPC(DebModCamera, "Reader", "Marccd");

 public:
    Reader(Camera& cam, HwBufferCtrlObj& buffer_ctrl);
    ~Reader();

    void start();
    void reset();
    int  getLastAcquiredFrame(void);

  //- [yat::Task implementation]
  protected: 
    virtual void handle_message( yat::Message& msg )    throw (yat::Exception);

		virtual void getImageFromFile();

 private:
    //- Mutex
    yat::Mutex                  lock_;
    yat::Mutex                  contextual_lock_;
    Camera&                     m_cam;
    HwBufferCtrlObj&            m_buffer;
    int                         m_image_number;
    
    //- Loading image stuff!
    Size                        m_image_size;
		DI::DiffractionImage*       m_DI;

		std::string									_currentImgFileName;	//- new image to read
		std::string									_previousImgFileName;	//- last image read

};
} // namespace Marccd
} // namespace lima

#endif // MARCCDREADER_H
